name: docs-preview-cleanup
on:
  pull_request_target:
    branches: [main]
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@654b6ff08ab5a5cb2c17b1cfc79b82db0dedb879 # v1
