name: docs-deploy
on:
  workflow_run:
    workflows: [docs-build]
    types: [completed]
permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write
  actions: read
jobs:
  deploy:
    uses: elastic/docs-actions/.github/workflows/docs-deploy.yml@654b6ff08ab5a5cb2c17b1cfc79b82db0dedb879 # v1
